Creating a game
hrederik/FirstTask pull request #1
Opened 2019-12-10 21:38 UTC by hrederik

2019-12-14 21:13 UTC, Powertr1p commented on Assets/Scripts/Barriers/Barrier.cs
> +        if (other.gameObject.tag == "Player")
Надо отказываться от поиска по тэгу, так как в нем идет проверка по стрингу, а в стринге легко сделать случайную ошибку, которая потом может сломать логику.

2019-12-14 21:13 UTC, Powertr1p commented on Assets/Scripts/Barriers/Barrier.cs
> +public class Barrier : MonoBehaviour
Название класса не отражает его ответственность и реализацию. Когда ты называешь класс — ты создаешь некую абстрактную модель, из названия которой, другой программист должен понять его реализацию.
А у тебя получается,  что ты назвал класс "барьер" — по-логике, он что-то ограничивает. Но когда мы смотрим на реализацию класса, мы видим, что он не ограничивает, а вызывает другую абстракцию GameOver, которая точно не ассоциируется с барьером, но с концом игры. Подумай тщательнее над названием класса и его реализацией.

2019-12-14 21:13 UTC, Powertr1p commented on Assets/Scripts/Diamonds/CollectDiamond.cs
> +		if (collider.tag == "Player")
Мы отказываемся от любых проверок, которые идут по стрингу.

2019-12-14 21:13 UTC, Powertr1p commented on Assets/Scripts/Diamonds/CollectDiamond.cs
> +public class CollectDiamond : MonoBehaviour
Лучше отдать эту реализацию в игрока. У тебя сейчас получается, что некий объект (diamond), который лежит на сцене сам решает когда его поднимают. Это странно. По твоей логике получается так, что игрок бегает по сцене, не зная, что он поднимает алмазы.

2019-12-14 21:13 UTC, Powertr1p commented on Assets/Scripts/GameManager.cs
> +		UserInterface.instance.UpdateScoreLabel(Scores);
Лучше сделать событием

2019-12-14 21:13 UTC, Powertr1p commented on Assets/Scripts/GameManager.cs
> +public class GameManager : Singletone<GameManager>
Название класса Manager — очень плохое, так как оно четко не обозначает границы ответственности класса.
Посмотри урок Романа о подобных названиях: https://www.youtube.com/watch?v=VNX6XfO81pE

2019-12-14 21:13 UTC, Powertr1p commented on Assets/Scripts/GameManager.cs
> +        if (_player)
У тебя есть поле _player, которое изначально подразумевает игрока. Ну то есть, игра, как процесс, не может существовать без игрока (иначе получается парадокс), но вот тут ты проверяешь существует ли игрок. Это странно.

2019-12-14 21:13 UTC, Powertr1p commented on Assets/Scripts/GameManager.cs
> +	public void RestartGame()
этот метод не должен быть публичным. Он может вызываться через событие и должен быть private.

2019-12-14 21:13 UTC, Powertr1p commented on Assets/Scripts/GameManager.cs
> +		UserInterface.instance.UpdateScoreLabel(Scores);
Метод AddScores не имеет смысла. Так как ты суммируешь amount, в Scores и сразу же отдаешь в другой класс. Так суммируй сразу в другом классе.

2019-12-14 21:13 UTC, Powertr1p commented on Assets/Scripts/Interface/MainMenu.cs
> +        _authorsPanel.SetBool("IsOpen", !_authorsPanel.GetBool("IsOpen"));
Вместо !_authorsPanel.GetBool("IsOpen") лучше явно привести флаг. Ты пишешь код не для себя, а для других программистов, которые будут его читать. Чем понятнее и очевиднее будет твой код, тем лучше.

2019-12-14 21:13 UTC, Powertr1p commented on Assets/Scripts/Singletone.cs
> +}
Если ты создаешь синглтон отдельным обобщенным классом — ты должен четко понимать зачем ты это делаешь. Как минимум, у тебя здесь нет разрушения другого синглтона, который может объявиться в сцене. Продумай все сценарии синглтона и реализуй их.

2019-12-14 21:13 UTC, Powertr1p commented on Assets/Scripts/Player/Player.cs
> +        }
Не критично, но можно убрать { }

2019-12-14 21:13 UTC, Powertr1p commented on Assets/Scripts/Player/GroundChecker.cs
> +}
SRP это хорошо, но я бы предложил перенести это в игрока, так как эту реализацию будет использовать только игрок и никто больше.

2019-12-14 21:13 UTC, Powertr1p commented on Assets/Scripts/Player/CameraFollow.cs
> +}
Просто сделай камеру дочерним объектом игрока в иерархии на сцене. Целый класс не стоит таких ресурсов.

2019-12-14 21:13 UTC, Powertr1p commented on Assets/Scripts/Platforms/PlatformGenerator.cs
> +        Invoke("Generate", _generateDelay);
Опять же тут инвоук идет через стринг — это плохо. Лучше иcпользовать StartCoroutine()

2019-12-14 21:13 UTC, Powertr1p commented on Assets/Scripts/Platforms/PlatformGenerator.cs
> +    private void Generate()
Сделать корутиной

2019-12-14 21:13 UTC, Powertr1p commented on Assets/Scripts/Platforms/PlatformGenerator.cs
> +        temp.GetComponent<BarrierGenerator>().Generate();
переменная с именем temp служит для хранения временных данных. А ты вызываешь через нее другие методы других классов.

2019-12-14 21:13 UTC, Powertr1p commented on Assets/Scripts/Platforms/PlatformExit.cs
> +        if (other.gameObject.tag == "Player")
Поиск по стринге, не делай так. В стринге легко ошибиться, потом хрен найдешь ошибку.

2019-12-14 21:13 UTC, Powertr1p commented on Assets/Scripts/Platforms/PlatformExit.cs
> +            gameObject.GetComponentInParent<PlatformGenerator>().StartGenerate();
Лучше это сделать событием

2019-12-14 21:13 UTC, Powertr1p commented on Assets/Scripts/Interface/UserInterface.cs
> +		if (_scoreLabel)
Насколько я понимаю, _scoreLabel должен существовать обязательно, так зачем же проверка? Если это дебагинг, то на релизной версии надо убрать

2019-12-14 21:13 UTC, Powertr1p commented on Assets/Scripts/Interface/UserInterface.cs
> +    public void GameOver()
Лучше сделать private и событие. Зачем? Любой другой программист, который будет дополнять твой код не сможет просто так вызвать этот метод и сломать логику игры.

2019-12-14 21:13 UTC, Powertr1p commented on Assets/Scripts/Diamonds/DiamondsGenerator.cs
> +        DisableDiamonds();
Когда ты создаешь методы, ты создаешь абстрактные понятия. Как читается твой код, так и другие программисты понимают твои намерения. Сейчас это выглядит так: "когда начинается игра (Start()), начать генерацию и сразу же отключить бриллианты". Это не несет никакой логики. Пожалуйста, пиши методы так, чтобы они могли рассказать цельную историю.

2019-12-14 21:13 UTC, Powertr1p commented on Assets/Scripts/Diamonds/DiamondsGenerator.cs
> +        }
Не критично, но для легкости чтения { } можно убрать

2019-12-14 21:13 UTC, Powertr1p commented on Assets/Scripts/Diamonds/DiamondsGenerator.cs
> +    }
Неправильно выбрано название. Генерация — производство чего-либо из чего-либо. А тут у тебя оказывается, что в методе Generate() вообще отключение бриллиантов.

2019-12-14 21:13 UTC, Powertr1p commented on Assets/Scripts/Barriers/BarrierGenerator.cs
> +            _barriers[i].SetActive(random <= 5);
Очень опасная формулировка, которая при изменении нескольких положений может легко сломаться. Я бы предложил описать так, чтобы барьеры ни при каких других условиях точно не сломались.

2019-12-15 07:44 UTC, GrechkoAA commented on Assets/Scripts/Barriers/Barrier.cs
> +﻿using System.Collections;
Убрать лишний using

2019-12-15 07:44 UTC, GrechkoAA commented on Assets/Scripts/Barriers/BarrierGenerator.cs
> +using System.Collections.Generic;
// Убрать лишний using

2019-12-15 07:45 UTC, GrechkoAA commented on Assets/Scripts/Barriers/BarrierGenerator.cs
> +        int random;
эта переменная не нужна. Random.Range(0, 12); добавь сразу в SetActive

2019-12-15 07:46 UTC, GrechkoAA commented on Assets/Scripts/Diamonds/CollectDiamond.cs
> +public class CollectDiamond : MonoBehaviour
Именуй классы существительным

2019-12-15 07:47 UTC, GrechkoAA commented on Assets/Scripts/Diamonds/CollectDiamond.cs
> +﻿using System;
// Убрать лишний using

2019-12-15 07:47 UTC, GrechkoAA commented on Assets/Scripts/Diamonds/DiamondsGenerator.cs
> +using System.Collections.Generic;
// Убрать лишний using

2019-12-15 07:48 UTC, GrechkoAA commented on Assets/Scripts/GameManager.cs
> +using UnityEngine.Events;
// Убрать лишний using

2019-12-15 07:49 UTC, GrechkoAA commented on Assets/Scripts/GameManager.cs
> +	public static int Scores { get; private set; }
1.Из названия класса, не понятно что за переменная. 2 Переменной, не место в этом классе.

2019-12-15 07:49 UTC, GrechkoAA commented on Assets/Scripts/GameManager.cs
> +	public void AddScores(int amount)
// Этому методу тут не место, у класса другая логика.

2019-12-15 07:50 UTC, GrechkoAA commented on Assets/Scripts/Interface/MainMenu.cs
> +using System.Collections.Generic;
// Убрать лишний using

2019-12-15 07:50 UTC, GrechkoAA commented on Assets/Scripts/Interface/UserInterface.cs
> +	[Space]
// В одну строку [Space, SerializeField]

2019-12-15 07:51 UTC, GrechkoAA commented on Assets/Scripts/Platforms/PlatformExit.cs
> +public class PlatformExit : MonoBehaviour
// Лучше именовать как класс Platform. Не желательно на каждое поведение создавать класс.

2019-12-15 07:52 UTC, GrechkoAA commented on Assets/Scripts/Platforms/PlatformGenerator.cs
> +﻿using System.Collections;
// Убрать лишний using

2019-12-15 07:52 UTC, GrechkoAA commented on Assets/Scripts/Platforms/PlatformGenerator.cs
> +    [SerializeField] private float _generateDelay = 2;
// Просто _delay, тут и так понятно по имени класса.

2019-12-15 07:53 UTC, GrechkoAA commented on Assets/Scripts/Platforms/PlatformGenerator.cs
> +        temp.GetComponent<DiamondsGenerator>().Generate();
// лучше использовать событие

2019-12-15 07:54 UTC, GrechkoAA commented on Assets/Scripts/Platforms/PlatformGenerator.cs
> +        temp.GetComponent<BarrierGenerator>().Generate();
// лучше использовать событие

2019-12-15 07:56 UTC, GrechkoAA commented on Assets/Scripts/Platforms/PlatformGenerator.cs
> +    public void StartGenerate()
// Unty рекомендует использовать корутины в место Invoke, но корутины тут тоже не нужны. Добавь таймер

2019-12-15 07:56 UTC, GrechkoAA commented on Assets/Scripts/Platforms/PlatformGenerator.cs
> +        _platforms.RemoveAt(0);
// это другая логика

2019-12-15 07:57 UTC, GrechkoAA commented on Assets/Scripts/Player/CameraFollow.cs
> +using System.Collections.Generic;
// Убрать лишний using

2019-12-15 07:57 UTC, GrechkoAA commented on Assets/Scripts/Player/CameraFollow.cs
> +    [SerializeField] private GameObject _target;
// нам нужен тип Transform a не GameObject

2019-12-15 07:58 UTC, GrechkoAA commented on Assets/Scripts/Player/CameraFollow.cs
> +        transform.position = new Vector3(transform.position.x, transform.position.y, _target.transform.position.z);
// Вынести в метод Follow
// Эту часть тоже вынести в другой метод GetTarget - transform.position.x, transform.position.y, _target.transform.position.z

2019-12-15 07:58 UTC, GrechkoAA commented on Assets/Scripts/Player/GroundChecker.cs
> +using System.Collections.Generic;
// Убрать лишний using

2019-12-15 07:59 UTC, GrechkoAA commented on Assets/Scripts/Player/GroundChecker.cs
> +public class GroundChecker : MonoBehaviour
// Если класс Player не переименовывать в PlayerMovement, то эту логику лучше перенести в класс Player

2019-12-15 07:59 UTC, GrechkoAA commented on Assets/Scripts/Player/GroundChecker.cs
> +    [SerializeField] private LayerMask _whatIsGround;
// просто _ground

2019-12-15 08:00 UTC, GrechkoAA commented on Assets/Scripts/Player/GroundChecker.cs
> +    public bool CheckGround()
// проверяется в условии, лучше именовать как IsGroung. Используй лямбда выражение.

2019-12-15 08:00 UTC, GrechkoAA commented on Assets/Scripts/Player/Player.cs
> +public class Player : MonoBehaviour
// Эта сущность отвечает за перемещение, лучше именовать PlayerMovement

2019-12-15 08:01 UTC, GrechkoAA commented on Assets/Scripts/Player/Player.cs
> +	private void Start()
// инициализировать компоненты лучше в Awake

2019-12-15 08:01 UTC, GrechkoAA commented on Assets/Scripts/Player/Player.cs
> +            Jump();
// физику лучше вызывать в FixedUpdate

2019-12-15 08:01 UTC, GrechkoAA commented on Assets/Scripts/Player/Player.cs
> +        _rigidbody.velocity = new Vector3(_rigidbody.velocity.x, _rigidbody.velocity.y, _speed);
// вынести в метод

2019-12-15 08:02 UTC, GrechkoAA commented on Assets/Scripts/Singletone.cs
> +	public static T instance
// используй PascalCase

2019-12-16 13:01 UTC, Lexv0lk commented on Assets/Scripts/Barriers/Barrier.cs
> +        if (other.gameObject.tag == "Player")
Проверяй по компоненту, не по тегу

2019-12-16 13:01 UTC, Lexv0lk commented on Assets/Scripts/Barriers/BarrierGenerator.cs
> +        int random;
В данном случае либо объявляй её в теле цикла, либо откажись от переменной

2019-12-16 13:01 UTC, Lexv0lk commented on Assets/Scripts/Diamonds/CollectDiamond.cs
> +public class CollectDiamond : MonoBehaviour
При названии класса используй существительные

2019-12-16 13:01 UTC, Lexv0lk commented on Assets/Scripts/Diamonds/CollectDiamond.cs
> +		if (collider.tag == "Player")
Не проверяй по тегу, проверяй по компоненту

2019-12-16 13:01 UTC, Lexv0lk commented on Assets/Scripts/Diamonds/CollectDiamond.cs
> +            GameManager.instance.AddScores(_scoreAmount);
Класс не должен зависеть от GameManager, подойдут события

2019-12-16 13:01 UTC, Lexv0lk commented on Assets/Scripts/Diamonds/DiamondsGenerator.cs
> +        endPoint = Random.Range(startPoint, _diamonds.Length - 1);
при объявлении можешь сразу инициализировать переменные

2019-12-16 13:01 UTC, Lexv0lk commented on Assets/Scripts/GameManager.cs
> +public class GameManager : Singletone<GameManager>
1. Старайся избавляться от менеджеров - классов, отвечающих за все и вся без границ своего функционала.
2. Подумай над архитектурой кода, где каждый может обратиться к менеджеру и перезапустить игру, правильно ли это?
3. Тебе не нужен синглтон, наследуй от MonoBehaviour

2019-12-16 13:01 UTC, Lexv0lk commented on Assets/Scripts/GameManager.cs
> +	public static int Scores { get; private set; }
Должно ли это быть в этом классе?

2019-12-16 13:01 UTC, Lexv0lk commented on Assets/Scripts/GameManager.cs
> +		UserInterface.instance.UpdateScoreLabel(Scores);
Получай доступ к таким класса, путем задания зависимостей через инспектор, но не через .instance

2019-12-16 13:01 UTC, Lexv0lk commented on Assets/Scripts/GameManager.cs
> +	public void AddScores(int amount)
Выдели отдельный класс, который будет заниматься очками, это не ответственность GameManager

2019-12-16 13:01 UTC, Lexv0lk commented on Assets/Scripts/GameManager.cs
> +		UserInterface.instance.UpdateScoreLabel(Scores);
Избавляйся от передачи зависимостей через .instance, у тебя есть инспектор

2019-12-16 13:01 UTC, Lexv0lk commented on Assets/Scripts/GameManager.cs
> +		UserInterface.instance.UpdateScoreLabel(Scores);
Должен ли GameManager зависеть от UI?

2019-12-16 13:01 UTC, Lexv0lk commented on Assets/Scripts/Interface/UserInterface.cs
> +
Лишняя пустая строка

2019-12-16 13:01 UTC, Lexv0lk commented on Assets/Scripts/Interface/UserInterface.cs
> +public class UserInterface : Singletone<UserInterface>
1. Тебе не нужен синглтон
2. Как и в случае с GameManager получается, что все вызывают UI, сделай это через события, тогда у тебя нельзя будет сломать игру, вызвав UI не пойми когда и откуда

2019-12-16 13:01 UTC, Lexv0lk commented on Assets/Scripts/Interface/UserInterface.cs
> +		if (_scoreLabel)
Лишняя проверка на зависимость из инспектора

2019-12-16 13:01 UTC, Lexv0lk commented on Assets/Scripts/Interface/UserInterface.cs
> +    }
Должен ли UI заниматься загрузкой сцен? Раздели ответственности

2019-12-16 13:01 UTC, Lexv0lk commented on Assets/Scripts/Platforms/PlatformExit.cs
> +        if (other.gameObject.tag == "Player")
Делай поиск по компоненту, не по тегу

2019-12-16 13:01 UTC, Lexv0lk commented on Assets/Scripts/Platforms/PlatformExit.cs
> +            gameObject.GetComponentInParent<PlatformGenerator>().StartGenerate();
Почему бы не получить эту зависимость в инспекторе?

2019-12-16 13:01 UTC, Lexv0lk commented on Assets/Scripts/Platforms/PlatformExit.cs
> +public class PlatformExit : MonoBehaviour
Подумай над названием, оно не должно выражаться глаголом

2019-12-16 13:01 UTC, Lexv0lk commented on Assets/Scripts/Platforms/PlatformGenerator.cs
> +public class PlatformGenerator : Singletone<PlatformGenerator>
Избавляйся от синглтонов

2019-12-16 13:01 UTC, Lexv0lk commented on Assets/Scripts/Platforms/PlatformGenerator.cs
> +        Invoke("Generate", _generateDelay);
Не используй invoke, корутины подойдут лучше

2019-12-16 13:01 UTC, Lexv0lk commented on Assets/Scripts/Platforms/PlatformGenerator.cs
> +        GameObject temp = _platforms[0];
Нужна ли эта переменная, правильное ли у нее название?

2019-12-16 13:01 UTC, Lexv0lk commented on Assets/Scripts/Platforms/PlatformGenerator.cs
> +        temp.GetComponent<BarrierGenerator>().Generate();
Для упрощения таких вещей лучше вынести абстрактный класс Generator

2019-12-16 13:01 UTC, Lexv0lk commented on Assets/Scripts/Player/CameraFollow.cs
> +public class CameraFollow : MonoBehaviour
Подумай над названием класса, это не должен быть глагол

2019-12-16 13:01 UTC, Lexv0lk commented on Assets/Scripts/Singletone.cs
> +public class Singletone<T> : MonoBehaviour where T : MonoBehaviour
Тебе не нужны синглтоны, они портят архитектуру кода, создавая классы, которые делают все и которых ты можешь вызвать отовсюду, вместо этого используй внедрение зависимостей через инспектор, либо DI

2019-12-18 17:41 UTC, HolyMonkey requested changes

2019-12-18 17:41 UTC, HolyMonkey commented on Assets/Scripts/Barriers/Barrier.cs
> +public class Barrier : MonoBehaviour
В целом барьер тут ок. Можно уточнить до DeathTriger, но в целом норм. Барьер - это предметное название тригера.

2019-12-18 17:41 UTC, HolyMonkey commented on Assets/Scripts/Barriers/Barrier.cs
> +        if (other.gameObject.tag == "Player")
Согласен

2019-12-18 17:41 UTC, HolyMonkey commented on Assets/Scripts/Barriers/BarrierGenerator.cs
> +        int random;
Оба не правы. Нужен метод который возвращает случайный bool с определённым шансом на true

2019-12-18 17:41 UTC, HolyMonkey commented on Assets/Scripts/Barriers/BarrierGenerator.cs
> +            _barriers[i].SetActive(random <= 5);
Согласен. Сейчас на сцене заранее раставляются барьеры и случайным образом включаются. Нужна генерация новых барьеров по ходу движения игрока

2019-12-18 17:41 UTC, HolyMonkey commented on Assets/Scripts/Diamonds/CollectDiamond.cs
> +public class CollectDiamond : MonoBehaviour
Это нормально. У игрока своя ответсвеность а сбор алмазов выделен в отдельный комплекс классов.

2019-12-18 17:41 UTC, HolyMonkey commented on Assets/Scripts/Diamonds/CollectDiamond.cs
> +public class CollectDiamond : MonoBehaviour
Согласен
CollectableDiamon например

2019-12-18 17:41 UTC, HolyMonkey commented on Assets/Scripts/Diamonds/DiamondsGenerator.cs
> +        DisableDiamonds();
Тут пограничная ситуация. Вообще я считаю что при старте компоненты могут приводить данные к изначальному виду.

2019-12-18 17:41 UTC, HolyMonkey commented on Assets/Scripts/Diamonds/DiamondsGenerator.cs
> +        endPoint = Random.Range(startPoint, _diamonds.Length - 1);
Согласен

2019-12-18 17:41 UTC, HolyMonkey commented on Assets/Scripts/GameManager.cs
> +public class GameManager : Singletone<GameManager>
Согласен

2019-12-18 17:41 UTC, HolyMonkey commented on Assets/Scripts/GameManager.cs
> +	public static int Scores { get; private set; }
Согласен

2019-12-18 17:41 UTC, HolyMonkey commented on Assets/Scripts/GameManager.cs
> +		UserInterface.instance.UpdateScoreLabel(Scores);
Согласен

2019-12-18 17:41 UTC, HolyMonkey commented on Assets/Scripts/GameManager.cs
> +		UserInterface.instance.UpdateScoreLabel(Scores);
Согласен

2019-12-18 17:41 UTC, HolyMonkey commented on Assets/Scripts/GameManager.cs
> +	public void AddScores(int amount)
Согласен

2019-12-18 17:41 UTC, HolyMonkey commented on Assets/Scripts/GameManager.cs
> +		UserInterface.instance.UpdateScoreLabel(Scores);
Тот класс занимается UI

2019-12-18 17:41 UTC, HolyMonkey commented on Assets/Scripts/Interface/UserInterface.cs
> +public class UserInterface : Singletone<UserInterface>
Согласен

2019-12-18 17:41 UTC, HolyMonkey commented on Assets/Scripts/Interface/UserInterface.cs
> +    public void GameOver()
Верно, вызов GameOver тут не означает GameOver игры 
Также можно просто метод по другому назвать

2019-12-18 17:41 UTC, HolyMonkey commented on Assets/Scripts/Interface/UserInterface.cs
> +		if (_scoreLabel)
Верно. Если кто-то забыл назначить должна быть ошибка а не просто "ничего"

2019-12-18 17:41 UTC, HolyMonkey commented on Assets/Scripts/Interface/UserInterface.cs
> +    }
В данном случае загрузкой сцен занимается SceneManager так, что всё норм

2019-12-18 17:41 UTC, HolyMonkey commented on Assets/Scripts/Platforms/PlatformExit.cs
> +            gameObject.GetComponentInParent<PlatformGenerator>().StartGenerate();
Согласен

2019-12-18 17:41 UTC, HolyMonkey commented on Assets/Scripts/Platforms/PlatformExit.cs
> +public class PlatformExit : MonoBehaviour
Согласен

2019-12-18 17:41 UTC, HolyMonkey commented on Assets/Scripts/Platforms/PlatformGenerator.cs
> +    [SerializeField] private float _generateDelay = 2;
Согласен

2019-12-18 17:41 UTC, HolyMonkey commented on Assets/Scripts/Platforms/PlatformGenerator.cs
> +        Invoke("Generate", _generateDelay);
Согласен

2019-12-18 17:41 UTC, HolyMonkey commented on Assets/Scripts/Platforms/PlatformGenerator.cs
> +        GameObject temp = _platforms[0];
Согласен

2019-12-18 17:41 UTC, HolyMonkey commented on Assets/Scripts/Player/CameraFollow.cs
> +public class CameraFollow : MonoBehaviour
Поведение может выражаться глаголом, например FollowTarget - это адекватное название

2019-12-18 17:41 UTC, HolyMonkey commented on Assets/Scripts/Player/CameraFollow.cs
> +}
Вероятней всего игрок включается\выключается

2019-12-18 17:41 UTC, HolyMonkey commented on Assets/Scripts/Player/Player.cs
> +public class Player : MonoBehaviour
Согласен

2019-12-18 17:41 UTC, HolyMonkey commented on Assets/Scripts/Singletone.cs
> +public class Singletone<T> : MonoBehaviour where T : MonoBehaviour
Согласен

2020-01-14 23:40 UTC, HolyMonkey requested changes

2020-01-14 23:40 UTC, HolyMonkey commented on Assets/Scripts/Barriers/BarrierGenerator.cs
> +    [SerializeField] private GameObject[] _barriers;
Нет, объекты должны именно бесконечно генерироваться

2020-01-14 23:40 UTC, HolyMonkey commented on Assets/Scripts/Barriers/DeathTriger.cs
> +        _interface = FindObjectOfType<UserInterface>();
Используй явное назначение зависимостей через инспектор вместо поиска объекта на сцене

2020-01-14 23:40 UTC, HolyMonkey commented on Assets/Scripts/Diamonds/CollectableDiamond.cs
> +		}
Поправь форматирование

2020-01-14 23:40 UTC, HolyMonkey commented on Assets/Scripts/Interface/MainMenu.cs
> +        _authorsPanel.SetBool("IsOpen", !_authorsPanel.GetBool("IsOpen"));
Нет, флаг тут к сожалению не будет лучшим решением

2020-01-21 15:09 UTC, HolyMonkey requested changes

2020-01-21 15:09 UTC, HolyMonkey commented on Assets/Scripts/Barriers/DeathTriger.cs
> +
PlayerTrigger тогда уж

2020-01-21 15:09 UTC, HolyMonkey commented on Assets/Scripts/Diamonds/CollectableDiamond.cs
> +		if (collider.transform.GetComponent<PlayerMovement>())
У тебя уже есть компонент который занимается реагированием на игрока и даже есть событие

2020-01-21 15:09 UTC, HolyMonkey commented on Assets/Scripts/Diamonds/CollectableDiamond.cs
> +        _scores = FindObjectOfType<Scores>();
Мы не используем FindObjectOfType

2020-01-21 15:09 UTC, HolyMonkey commented on Assets/Scripts/Interface/UserInterface.cs
> +        _scores.UpdateScores += UpdateScoreLabel;
https://trello.com/c/CsOZfMhi/1-%D0%BD%D0%B0%D0%B7%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F-%D1%81%D0%BE%D0%B1%D1%8B%D1%82%D0%B8%D0%B9-%D0%BE%D0%B1%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%87%D0%B8%D0%BA%D0%BE%D0%B2

2020-01-21 15:09 UTC, HolyMonkey commented on Assets/Scripts/Platforms/PlatformGenerator.cs
> +        temp.GetComponent<BarrierGenerator>().Generate();
Согласен

2020-02-16 14:00 UTC, HolyMonkey requested changes

2020-02-16 14:00 UTC, HolyMonkey commented on Assets/Scripts/Diamonds/CollectableDiamond.cs
> +		if (IsPlayer(collider))
Поправь форматирование

2020-02-16 14:00 UTC, HolyMonkey commented on Assets/Scripts/Diamonds/CollectableDiamond.cs
> +    }
Нет смысла так разворачивать событие

2020-02-16 14:00 UTC, HolyMonkey commented on Assets/Scripts/Diamonds/CollectableDiamond.cs
> +    [SerializeField] private int _scoreAmount = 1;
Просто _score

2020-02-21 20:46 UTC, HolyMonkey requested changes

2020-02-21 20:46 UTC, HolyMonkey commented on Assets/Scripts/Barriers/BarrierGenerator.cs
> +        }
Зачем вносить несвязность в таком случае? Сдеай обработчик OnBarrierHit  и в нём вызывай StopGame ShowGameOverUI

2020-02-21 20:46 UTC, HolyMonkey commented on Assets/Scripts/Diamonds/CollectableDiamond.cs
> +public class CollectableDiamond : MonoBehaviour
Просто Diamond

2020-02-21 20:46 UTC, HolyMonkey commented on Assets/Scripts/Diamonds/DiamondsGenerator.cs
> +public class DiamondsGenerator : MonoBehaviour
Частично дублирует BarrierGenerator

2020-02-21 20:46 UTC, HolyMonkey commented on Assets/Scripts/Player/PlayerCollider.cs
> +    public UnityAction HitEvent;
Ты забыл event и события так не называются

2020-02-21 20:46 UTC, HolyMonkey commented on Assets/Scripts/Player/PlayerCollider.cs
> +public class PlayerCollider : MonoBehaviour
PlayerTrigger

2020-02-21 20:46 UTC, HolyMonkey commented on Assets/Scripts/Player/PlayerCollider.cs
> +    }
Точно такой же код у тебя в Diamond

2020-03-03 12:01 UTC, HolyMonkey requested changes

2020-03-03 12:01 UTC, HolyMonkey commented on Assets/Scripts/Generator.cs
> +    public GameObject[] Objects;
Мы не используем публичные поля

2020-03-03 12:01 UTC, HolyMonkey commented on Assets/Scripts/Generator.cs
> +    }
Помести этот метод под метод Generate

2020-03-03 12:01 UTC, HolyMonkey commented on Assets/Scripts/Generator.cs
> +    }
Публичные методы перед приватными а перед публичным должны быть приватные методы Unity

2020-03-03 12:01 UTC, HolyMonkey commented on Assets/Scripts/Diamonds/Diamond.cs
> +    public event UnityAction<int> DiamondCollected;
Collected

2020-03-03 12:01 UTC, HolyMonkey commented on Assets/Scripts/Diamonds/Diamond.cs
> +public class Diamond : MonoBehaviour
Дублирует PlayerTrigger

2020-03-03 12:01 UTC, HolyMonkey commented on Assets/Scripts/Barriers/BarrierGenerator.cs
> +public class BarrierGenerator : Generator
Тут нет ничего ничего от генерации, это не генератор

2020-03-03 12:01 UTC, HolyMonkey commented on Assets/Scripts/Diamonds/DiamondsGenerator.cs
> +public class DiamondsGenerator : Generator
Тут нет ничего ничего от генерации, это не генератор

2020-03-03 12:01 UTC, HolyMonkey commented on Assets/Scripts/Generator.cs
> +public class Generator : MonoBehaviour
Он должен поставлять событие о создание нового объекта, на это событие подписываются и подписываются на события нужных объектов из всего потока

2020-03-16 20:30 UTC, HolyMonkey requested changes

2020-03-16 20:30 UTC, HolyMonkey commented on Assets/Scripts/Barrier/BarrierListenerProvider.cs
> +public class BarrierListenerProvider : MonoBehaviour, IListenerProvider
Какую задачу решает этот класс?

2020-03-16 20:30 UTC, HolyMonkey commented on Assets/Scripts/Barrier/BarrierListenerProvider.cs
> +    }
Бесмысленые методы

2020-03-16 20:31 UTC, HolyMonkey commented
В ближайший день жду на устном обсуждение, дам больше примеров. К сожалению не туда ты ушёл

2020-03-17 10:12 UTC, HolyMonkey requested changes

2020-03-17 10:12 UTC, HolyMonkey commented on Assets/Scripts/Player/PlayerTrigger.cs
> +
Убери это событие

2020-03-17 10:12 UTC, HolyMonkey commented on Assets/Scripts/Player/PlayerTrigger.cs
> +            _playerInteracted.Invoke();
Тут вызывается абстрактный метод OnPlayerEnter

2020-03-17 10:12 UTC, HolyMonkey commented on Assets/Scripts/Player/PlayerTrigger.cs
> +    }
Это надо удалить

2020-07-25 09:19 UTC, merged